#!/bin/bash

# This script will:
# 1. Copy all non-hidden files to your ~/.vim directory.
# 2. Set up symbolic links for `~/.gvimrc` and `~/.vimrc`.

DESTDIR=$HOME/.vim

SCRIPTDIR=$(dirname "$(readlink -f "$0")")


# Confirm that we really want to do this.
echo "Warning: This will overwrite '~/.vim', '~/.vimrc', and '~/.gvimrc'."
read -p "Do you wish to continue? (Yy): " -n 1 -r
echo

if [[ $REPLY =~ ^[^Yy]$ ]]; then
	echo Operation aborted.
	exit 1
fi

echo

if ! [ "$SCRIPTDIR" -ef "$DESTDIR" ]; then
	# Only copy the files if this script is not in the ~/.vim directory.
	rsync -av --exclude=".*" "$SCRIPTDIR/" "$DESTDIR"
	echo
fi

ln -sfv "$DESTDIR/vimrc" ~/.vimrc
ln -sfv "$DESTDIR/gvimrc" ~/.gvimrc

echo
echo "All done! Enjoy and code responsibly."
